name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    name: Node ${{ matrix.node }} build
    env:
      CREDS: ${{ secrets.CREDS }}
      BEAME_TESTS_LOCAL_FQDN: ${{ secrets.BEAME_TESTS_LOCAL_FQDN }}
      BEAME_TESTS_LOCAL_ROOT_FQDN: ${{ secrets.BEAME_TESTS_LOCAL_ROOT_FQDN }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install && npm test
      - run: echo $CREDS | base64 --decode > creds.tgz ; mkdir -p ~/.beame/v2 ; tar -xvzf creds.tgz -C ~/.beame/v2 ; make dev-unittests